# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'BookListApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookListApp
  # 图片加载库 (作业核心要求)
  pod 'SDWebImage', '~> 5.19'

  target 'BookListAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookListAppUITests' do
    # Pods for testing
  end

end


# 添加post_install脚本解决版本兼容问题
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
