# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'BookListApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookListApp
  # 图片加载库 (作业核心要求)
  pod 'SDWebImage', '~> 5.19'

  target 'BookListAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookListAppUITests' do
    # Pods for testing
  end

end
